import streamlit as st
import requests
import time
import base64
from PIL import Image
import io

# Page configuration
st.set_page_config(
    page_title="AI Jewel Design Generator",
    page_icon="💎",
    layout="wide"
)

# Custom CSS for beautiful design
st.markdown("""
<style>
    .main-header {
        font-size: 3rem;
        color: #4A4A4A;
        text-align: center;
        margin-bottom: 2rem;
    }
    .design-card {
        border: 2px solid #f0f0f0;
        border-radius: 15px;
        padding: 20px;
        margin: 10px;
        text-align: center;
        background: white;
        transition: transform 0.2s;
    }
    .design-card:hover {
        transform: translateY(-5px);
        box-shadow: 0 8px 16px rgba(0,0,0,0.1);
    }
    .stButton button {
        background: linear-gradient(45deg, #FF6B6B, #FF8E53);
        color: white;
        border: none;
        padding: 12px 24px;
        border-radius: 25px;
        cursor: pointer;
        font-size: 16px;
        font-weight: bold;
    }
    .success-box {
        background: linear-gradient(45deg, #4CAF50, #45a049);
        color: white;
        padding: 20px;
        border-radius: 10px;
        text-align: center;
        margin: 20px 0;
    }
    .ai-badge {
        background: linear-gradient(45deg, #FF6B6B, #FF8E53);
        color: white;
        padding: 5px 10px;
        border-radius: 15px;
        font-size: 12px;
        font-weight: bold;
        display: inline-block;
        margin-bottom: 10px;
    }
    .real-ai-notice {
        background: linear-gradient(45deg, #667eea, #764ba2);
        color: white;
        padding: 15px;
        border-radius: 10px;
        text-align: center;
        margin: 10px 0;
    }
</style>
""", unsafe_allow_html=True)

def generate_real_ai_design(prompt, api_key):
    """
    Generate REAL AI jewelry designs using Hugging Face API
    """
    try:
        # Hugging Face API for Stable Diffusion
        API_URL = "https://api-inference.huggingface.co/models/runwayml/stable-diffusion-v1-5"
        headers = {"Authorization": f"Bearer {api_key}"}
        
        # Enhanced prompt specifically for jewelry design
        enhanced_prompt = f"""
        professional jewelry design: {prompt}, 
        high quality, detailed, studio lighting, 
        perfect proportions, elegant jewelry piece,
        masterpiece, 8k resolution, clean white background,
        jewelry product photography, luxury item
        """
        
        payload = {
            "inputs": enhanced_prompt,
            "parameters": {
                "num_inference_steps": 25,
                "guidance_scale": 7.5,
                "width": 512,
                "height": 512
            },
            "options": {
                "wait_for_model": True,
                "use_cache": True
            }
        }
        
        # Show loading state
        with st.spinner("🔄 AI is creating your custom jewelry design..."):
            response = requests.post(API_URL, headers=headers, json=payload, timeout=120)
        
        if response.status_code == 200:
            return response.content
        else:
            st.error(f"AI API Error: {response.status_code}")
            if response.status_code == 503:
                st.info("AI model is loading... This can take 20-30 seconds on first use. Please try again!")
            return None
            
    except Exception as e:
        st.error(f"AI service error: {str(e)}")
        return None

# App title with AI badge
st.markdown('<h1 class="main-header">💎 AI Jewel Design Generator</h1>', unsafe_allow_html=True)
st.markdown('<div class="real-ai-notice">🚀 <strong>REAL AI POWERED</strong> - Generates custom jewelry designs from your descriptions!</div>', unsafe_allow_html=True)

# Sidebar for API key and settings
with st.sidebar:
    st.header("🔑 AI Settings")
    
    # API Key input
    api_key = st.text_input(
        "Enter your Hugging Face API Key:",
        type="password",
        placeholder="hf_xxxxxxxxxxxxxxxx",
        help="Get free API key from huggingface.co → Settings → Access Tokens"
    )
    
    st.header("⚙️ Design Settings")
    num_designs = st.slider("Number of designs", 1, 3, 1)
    
    st.header("🎨 Style Options")
    material = st.selectbox("Material", ["Gold", "Silver", "Platinum", "Rose Gold", "Custom"])
    jewelry_type = st.selectbox("Type", ["Ring", "Necklace", "Earrings", "Bracelet", "Custom"])
    
    st.markdown("---")
    if api_key:
        st.success("✅ **AI Ready!** Your designs will be generated by real AI")
    else:
        st.info("🔑 **Enter API Key above** to enable real AI generation")
    st.info("💡 **Tip**: Be specific! The AI will create exactly what you describe.")

# Main content
col1, col2 = st.columns([2, 1])

with col1:
    st.subheader("✨ Describe Your Jewelry Design")
    
    # AI-optimized example prompts
    example_prompts = [
        "Gold ring with intricate floral engraving and small diamond accents",
        "Elegant silver necklace with geometric pendant and emerald gemstone",
        "Rose gold earrings with pearl drops and vintage filigree details",
        "Platinum bracelet with art deco patterns and sapphire stones"
    ]
    
    st.write("**AI-optimized examples:**")
    cols = st.columns(2)
    for i, example in enumerate(example_prompts):
        with cols[i % 2]:
            if st.button(f"💎 {example[:25]}...", key=f"btn_{i}", use_container_width=True):
                st.session_state.prompt = example

    # Main input
    prompt = st.text_area(
        "Design description:",
        placeholder="Example: 'A gold ring with floral engraving, small diamond accents, vintage styling, elegant proportions'",
        height=120,
        key="prompt_input",
        value=st.session_state.get('prompt', '')
    )

with col2:
    st.subheader("🤖 AI Design Guide")
    st.markdown("""
    **For Best AI Results:**
    
    ✅ **Include:**
    - Material (gold, silver, etc.)
    - Jewelry type (ring, necklace, etc.)
    - Patterns (floral, geometric, etc.)
    - Gemstones (diamond, emerald, etc.)
    - Style (vintage, modern, etc.)
    
    🎯 **Example:**
    *"Gold ring with floral engraving, emerald center stone, vintage elegant style"*
    
    ⚡ **The AI will create this exactly!**
    """)

# Generation section
st.markdown("---")
st.subheader("🎨 Generate with AI")

if st.button("✨ Create with Real AI", type="primary", use_container_width=True):
    if not api_key:
        st.error("🔑 Please enter your Hugging Face API Key in the sidebar first!")
        st.info("Get free API key: huggingface.co → Settings → Access Tokens")
    elif not prompt:
        st.warning("⚠️ Please describe your jewelry design!")
    else:
        # Enhanced prompt with user selections
        full_prompt = prompt
        if material != "Custom":
            full_prompt = f"{material} {full_prompt}"
        if jewelry_type != "Custom":
            full_prompt = f"{jewelry_type}, {full_prompt}"
        
        st.markdown(f'<div class="ai-badge">AI GENERATING: "{full_prompt}"</div>', unsafe_allow_html=True)
        
        # Generate designs
        designs = []
        for i in range(num_designs):
            design_image = generate_real_ai_design(full_prompt, api_key)
            if design_image:
                designs.append(design_image)
            time.sleep(2)  # Rate limiting
        
        # Display results
        if designs:
            st.markdown(f'<div class="success-box">🎉 AI Generated {len(designs)} Unique Design(s)!</div>', unsafe_allow_html=True)
            
            # Display design cards
            design_cols = st.columns(len(designs))
            
            for i, design in enumerate(designs):
                with design_cols[i]:
                    st.markdown(f'<div class="design-card">', unsafe_allow_html=True)
                    st.markdown(f"### Design {i+1}")
                    st.markdown('<div class="ai-badge">AI CREATED</div>', unsafe_allow_html=True)
                    
                    # Display AI-generated image
                    st.image(design, use_column_width=True, caption=f"AI: {prompt}")
                    
                    # Download button
                    st.download_button(
                        label="📥 Download AI Design",
                        data=design,
                        file_name=f"ai_jewelry_design_{i+1}.png",
                        mime="image/png",
                        key=f"download_{i}",
                        use_container_width=True
                    )
                    st.markdown('</div>', unsafe_allow_html=True)
        else:
            st.error("❌ AI generation failed. Please check your API key and try again.")
            st.info("💡 First generation might take 20-30 seconds as the AI model loads.")

# Student benefits with AI
st.markdown("---")
st.markdown("""
### 🎓 AI-Powered Learning:

**With Real AI, Students Can:**
- ✅ **Create custom designs** that don't exist yet
- ✅ **Explore exact specifications** from text descriptions  
- ✅ **Generate unlimited variations** of the same concept
- ✅ **Build professional portfolios** with unique AI creations
- ✅ **Learn design principles** through AI experimentation
""")

# Footer
st.markdown("---")
st.markdown("""
<div style='text-align: center'>
    <p>🤖 <strong>Real AI Jewelry Designer</strong> - Creating custom designs from your imagination!</p>
    <p>✨ Text-to-Image AI • Unlimited Custom Designs • Perfect for Student Projects</p>
</div>
""", unsafe_allow_html=True)
